"""
Complete YOLO Training Pipeline for Mechanical Components Detection
Trains on synthetic data generated by Blender scripts
"""
import os
import shutil
import yaml
from pathlib import Path
import random

def setup_yolo_dataset(source_dir="desk_renders", output_dir="yolo_dataset"):
    """
    Convert generated synthetic data to YOLO training format
    Creates train/val splits and dataset.yaml
    """
    print("🚀 Setting up YOLO dataset structure...")
    
    # Create YOLO directory structure
    dataset_path = Path(output_dir)
    (dataset_path / "images" / "train").mkdir(parents=True, exist_ok=True)
    (dataset_path / "images" / "val").mkdir(parents=True, exist_ok=True)
    (dataset_path / "labels" / "train").mkdir(parents=True, exist_ok=True)
    (dataset_path / "labels" / "val").mkdir(parents=True, exist_ok=True)
    
    # Get all image/label pairs
    source_path = Path(source_dir)
    image_files = list(source_path.glob("render_*.jpg"))
    
    print(f"📊 Found {len(image_files)} training images")
    
    # Create train/validation split (80/20)
    random.shuffle(image_files)
    split_idx = int(len(image_files) * 0.8)
    train_images = image_files[:split_idx]
    val_images = image_files[split_idx:]
    
    print(f"📈 Training set: {len(train_images)} images")
    print(f"📉 Validation set: {len(val_images)} images")
    
    # Copy training files
    for img_file in train_images:
        label_file = img_file.with_suffix('.txt')
        if label_file.exists():
            # Copy image
            shutil.copy2(img_file, dataset_path / "images" / "train" / img_file.name)
            # Copy label
            shutil.copy2(label_file, dataset_path / "labels" / "train" / label_file.name)
    
    # Copy validation files
    for img_file in val_images:
        label_file = img_file.with_suffix('.txt')
        if label_file.exists():
            # Copy image
            shutil.copy2(img_file, dataset_path / "images" / "val" / img_file.name)
            # Copy label
            shutil.copy2(label_file, dataset_path / "labels" / "val" / label_file.name)
    
    # Create dataset.yaml for YOLO training
    classes = {
        0: "small_screw",
        1: "small_hole", 
        2: "large_screw",
        3: "large_hole",
        4: "bracket_A",
        5: "bracket_B",
        6: "surface"
    }
    
    dataset_config = {
        'path': str(dataset_path.absolute()),
        'train': 'images/train',
        'val': 'images/val',
        'names': classes
    }
    
    with open(dataset_path / "dataset.yaml", 'w') as f:
        yaml.dump(dataset_config, f, default_flow_style=False)
    
    print(f"✅ Dataset ready at: {dataset_path.absolute()}")
    print(f"✅ Configuration saved: {dataset_path / 'dataset.yaml'}")
    
    return str(dataset_path.absolute())

def train_yolo_model(dataset_path, model_size="n", epochs=100, imgsz=640):
    """
    Train YOLO model using Ultralytics
    """
    print(f"🎯 Starting YOLO training (size={model_size}, epochs={epochs})...")
    
    try:
        from ultralytics import YOLO
        import torch
    except ImportError:
        print("❌ Ultralytics not installed. Installing...")
        os.system("pip install ultralytics torch")
        from ultralytics import YOLO
        import torch
    
    # Initialize model
    model = YOLO(f'yolo11{model_size}-seg.pt')  # Segmentation model
    
    # Train model
    results = model.train(
        data=f"{dataset_path}/dataset.yaml",
        epochs=epochs,
        imgsz=imgsz,
        device='0' if torch.cuda.is_available() else 'cpu',  # Use GPU if available
        project='runs/segment',
        name='mechanical_components',
        save=True,
        save_period=10,  # Save checkpoint every 10 epochs
        plots=True,
        verbose=True
    )
    
    print("✅ Training complete!")
    print(f"📁 Results saved to: runs/segment/mechanical_components")
    
    return results

def export_to_coreml(model_path, output_name="mechanical_components"):
    """
    Export trained model to Core ML format for iOS
    """
    print("📱 Exporting model to Core ML...")
    
    try:
        from ultralytics import YOLO
        import torch
    except ImportError:
        print("❌ Missing dependencies. Installing...")
        os.system("pip install ultralytics torch")
        from ultralytics import YOLO
        import torch
    
    # Load trained model
    model = YOLO(model_path)
    
    # Export to Core ML
    try:
        success = model.export(
            format='coreml',
            imgsz=640,
            nms=True,  # Include NMS in model
            half=False,  # Use FP32 for better iOS compatibility
        )
        
        if success:
            coreml_path = model_path.replace('.pt', '.mlpackage')
            print(f"✅ Core ML model exported: {coreml_path}")
            
            # Copy to iOS project directory
            ios_models_dir = "yolo-ios-app/YOLOiOSApp/YOLOiOSApp"
            if os.path.exists(ios_models_dir):
                final_path = f"{ios_models_dir}/{output_name}.mlpackage"
                shutil.move(coreml_path, final_path)
                print(f"📱 Model copied to iOS project: {final_path}")
                return final_path
            else:
                print(f"⚠️  iOS project not found. Model saved as: {coreml_path}")
                return coreml_path
        
    except Exception as e:
        print(f"❌ Export failed: {e}")
        return None

def main():
    """Complete training pipeline"""
    print("="*80)
    print("🤖 YOLO MECHANICAL COMPONENTS TRAINING PIPELINE")
    print("="*80)
    
    # Step 1: Setup dataset
    dataset_path = setup_yolo_dataset()
    
    # Step 2: Train model
    print("\n" + "="*50)
    results = train_yolo_model(dataset_path, model_size="n", epochs=50)
    
    # Step 3: Find best model
    best_model = "runs/segment/mechanical_components/weights/best.pt"
    if os.path.exists(best_model):
        print(f"✅ Best model found: {best_model}")
        
        # Step 4: Export to Core ML
        print("\n" + "="*50)
        coreml_model = export_to_coreml(best_model, "mechanical_components_v1")
        
        if coreml_model:
            print("\n" + "="*80)
            print("🎉 TRAINING PIPELINE COMPLETE!")
            print("="*80)
            print(f"📊 Training results: runs/segment/mechanical_components/")
            print(f"📱 iOS model ready: {coreml_model}")
            print("\nNext steps:")
            print("1. Update iOS app to use new model")
            print("2. Test on real device")
            print("3. Deploy to App Store")
        
    else:
        print(f"❌ Best model not found at: {best_model}")

if __name__ == "__main__":
    main()