"""Add webhook_urls to users

Revision ID: 26088dd29943
Revises: e7fdca1e9c7d
Create Date: 2025-12-06 11:48:45.295178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26088dd29943'
down_revision: Union[str, Sequence[str], None] = 'e7fdca1e9c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('webhook_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'webhook_urls')
    # ### end Alembic commands ###
